export let products = [
  {
    id: "1",
    name: "Book",
    tagline: "Read & Grow",
    description: "A must-read for every developer.",
    website: "https://example.com",
    category: "Books",
    image: "/images/book.jpg",
    submittedBy: "Atul",
    upvotes: 10,
    comments: [],
  },
  {
    id: "2",
    name: "Pen",
    tagline: "Write your future!",
    description: "Smooth writing experience.",
    website: "https://example.com",
    category: "Stationery",
    image: "/images/pen.jpg",
    submittedBy: "Atul",
    upvotes: 8,
    comments: [],
  },
  {
    id: "3",
    name: "Laptop",
    tagline: "Powerful and portable",
    description: "Perfect for coding, gaming, and everything in between.",
    website: "https://example.com",
    category: "Tech",
    image: "/images/laptop.jpg",
    submittedBy: "Atul",
    upvotes: 15,
    comments: [],
  },
  {
    id: "4",
    name: "Headphones",
    tagline: "Crystal-clear sound",
    description: "Noise-cancelling wireless headphones for ultimate focus.",
    website: "https://example.com",
    category: "Tech",
    image: "/images/headphone.jpg",
    submittedBy: "Atul",
    upvotes: 12,
    comments: [],
  },
  {
    id: "5",
    name: "Coffee Mug",
    tagline: "Fuel your coding sessions",
    description: "Keeps your coffee warm and your mind sharp!",
    website: "https://example.com",
    category: "Lifestyle",
    image: "/images/mug.jpg",
    submittedBy: "Atul",
    upvotes: 7,
    comments: [],
  },
  {
    id: "6",
    name: "Smartphone",
    tagline: "Stay connected",
    description: "Your ultimate productivity companion.",
    website: "https://example.com",
    category: "Tech",
    image: "/images/smartphone.jpg",
    submittedBy: "Atul",
    upvotes: 20,
    comments: [],
  },
  {
    id: "7",
    name: "Desk Lamp",
    tagline: "Brighten your workspace",
    description: "LED desk lamp to reduce eye strain.",
    website: "https://example.com",
    category: "Home",
    image: "/images/lamp.jpg",
    submittedBy: "Atul",
    upvotes: 6,
    comments: [],
  },
  {
    id: "8",
    name: "Backpack",
    tagline: "Carry your essentials",
    description: "Stylish and spacious backpack for work or travel.",
    website: "https://example.com",
    category: "Lifestyle",
    image: "/images/bag.jpg",
    submittedBy: "Atul",
    upvotes: 9,
    comments: [],
  },
  {
    id: "9",
    name: "Water Bottle",
    tagline: "Stay hydrated",
    description: "Eco-friendly and reusable water bottle.",
    website: "https://example.com",
    category: "Lifestyle",
    image: "/images/bottle.jpg",
    submittedBy: "Atul",
    upvotes: 4,
    comments: [],
  },
  {
    id: "10",
    name: "Keyboard",
    tagline: "Type like a pro",
    description: "Mechanical keyboard for ultimate typing experience.",
    website: "https://example.com",
    category: "Tech",
    image: "/images/keyboard.jpg",
    submittedBy: "Atul",
    upvotes: 14,
    comments: [],
  },
  {
    id: "11",
    name: "Chair",
    tagline: "Sit in comfort",
    description: "Ergonomic chair for long coding sessions.",
    website: "https://example.com",
    category: "Home",
    image: "/images/chair.jpg",
    submittedBy: "Atul",
    upvotes: 11,
    comments: [],
  },
  {
    id: "12",
    name: "Notebook",
    tagline: "Jot down ideas",
    description: "For quick notes, sketches, and brainstorming.",
    website: "https://example.com",
    category: "Stationery",
    image: "/images/book.jpg",
    submittedBy: "Atul",
    upvotes: 5,
    comments: [],
  },
  {
    id: "13",
    name: "Mouse",
    tagline: "Smooth control",
    description: "Precision mouse for work and play.",
    website: "https://example.com",
    category: "Tech",
    image: "/images/mouse.jpg",
    submittedBy: "Atul",
    upvotes: 13,
    comments: [],
  },
  {
    id: "14",
    name: "Tablet",
    tagline: "Your portable sketchbook",
    description: "Perfect for digital art and note-taking.",
    website: "https://example.com",
    category: "Tech",
    image: "/images/tablet.jpg",
    submittedBy: "Atul",
    upvotes: 16,
    comments: [],
  },
  {
    id: "15",
    name: "Camera",
    tagline: "Capture memories",
    description: "High-quality camera for stunning photos.",
    website: "https://example.com",
    category: "Tech",
    image: "/images/camera.jpg",
    submittedBy: "Atul",
    upvotes: 18,
    comments: [],
  },
];

export let comments = [];

export let userUpvotes = {};
